# Generated by Django 3.2.9 on 2021-11-27 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('store_adress', models.TextField(max_length=500)),
                ('store_city', models.CharField(max_length=50)),
                ('store_postal_code', models.BigIntegerField(max_length=10)),
                ('geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.geometry')),
            ],
        ),
    ]
