# Generated by Django 3.2.9 on 2021-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_properites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properites',
            name='store_postal_code',
            field=models.BigIntegerField(),
        ),
    ]
