# Generated by Django 3.2.9 on 2021-11-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_properites_store_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_instock', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='properites',
            name='geometry',
        ),
    ]
