# Generated by Django 3.2.9 on 2021-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20211127_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ManyToManyField(to='admins.Product')),
            ],
        ),
    ]
