# Generated by Django 3.2.9 on 2021-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Geometry',
            new_name='GeometryModel',
        ),
        migrations.RenameModel(
            old_name='Properites',
            new_name='ProperitesModel',
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='product',
            field=models.ManyToManyField(to='admins.ProductModel'),
        ),
    ]
