# Generated by Django 3.2.9 on 2021-11-27 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_auto_20211127_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrymodel',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=14, max_digits=16), size=2),
        ),
    ]
