# Generated by Django 3.2.9 on 2021-11-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_geometrymodel_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymodel',
            name='product',
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.productmodel'),
        ),
    ]
