# Generated by Django 3.2.9 on 2021-11-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20211127_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.storemodel'),
        ),
    ]
