# Generated by Django 3.2.9 on 2021-12-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_properitesmodel_store_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.inventorymodel'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.inventorymodel'),
        ),
    ]
