# Generated by Django 3.2.9 on 2021-12-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_ordersmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.storemodel'),
        ),
    ]
