# Generated by Django 3.2.9 on 2021-12-04 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_ordersmodel_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrymodel',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2),
        ),
    ]
